#==========================================================================
# Description: Compile allwinner h6 kernel
# Copyright (C) 2023 https://github.com/13584452567
# Copyright (C) 2023 https://github.com/ophub/kernel
#==========================================================================

name: Compile allwinner h6 kernel

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      kernel_source:
        description: "Select the kernel source"
        required: false
        default: "codesnas/linux-h6-6.6.y"
        type: choice
        options:
          - 13584452567
          - codesnas/linux-h6-6.6.y
      kernel_version:
        description: "Select kernel version"
        required: false
        default: "6.6.y"
        type: choice
        options:
          - 6.6.y
      kernel_auto:
        description: "Auto use the latest kernel"
        required: false
        default: true
        type: boolean
      delete_source:
        description: "Delete the source after compilation"
        required: false
        default: true
        type: boolean
      kernel_package:
        description: "Select compile package list"
        required: false
        default: "all"
        type: choice
        options:
          - all
          - dtbs
      kernel_toolchain:
        description: "Select the compilation toolchain"
        required: false
        default: "gcc"
        type: choice
        options:
          - clang
          - gcc
          - gcc-14.2
          - gcc-14.3
      compress_format:
        description: "Set the initrd compression format"
        required: false
        default: "xz"
        type: choice
        options:
          - xz
          - gzip
          - zstd
          - lzma
      docker_image:
        description: "Select Armbian docker image"
        required: false
        default: "bookworm"
        type: choice
        options:
          - trixie
          - bookworm
          - bullseye
          - noble
          - jammy
      kernel_sign:
        description: "Set the kernel custom signature"
        required: false
        default: "-zicai"
        type: choice
        options:
          - -zicai
          - -ophub
          - -happy-new-year
          - -dragon-boat-festival
          - -mid-autumn-festival
          - -happy-national-day
          - -merry-christmas
          - -spring-plowing
          - -summer-growing
          - -autumn-harvesting
          - -winter-storing
          - -yourname
      kernel_config:
        description: "Set the path of kernel .config"
        required: false
        default: "kernel-config/release/h6"
        type: choice
        options:
          - kernel-config/release/h6
          - false

env:
  TZ: Etc/UTC

jobs:
  build:
    runs-on: ubuntu-22.04-arm
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialization environment
        id: init
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi $(docker images -q) 2>/dev/null
          [[ -n "${AGENT_TOOLSDIRECTORY}" ]] && sudo rm -rf "${AGENT_TOOLSDIRECTORY}"
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android 2>/dev/null
          sudo swapoff -a
          sudo rm -f /swapfile /mnt/swapfile
          sudo -E apt-get -y update
          sudo -E apt-get -y purge azure-cli ghc* zulu* llvm* firefox google* dotnet* powershell openjdk* mongodb* moby* || true
          sudo -E apt-get -y install $(curl -fsSL https://tinyurl.com/ubuntu2204-build-armbian)
          sudo -E systemctl daemon-reload
          #sudo -E apt-get -y full-upgrade
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          sudo sed -i '/NVM_DIR/d;/skel/d' /root/{.bashrc,.profile}
          sudo rm -rf ~/{.cargo,.dotnet,.rustup}
          sudo -E timedatectl set-timezone "${TZ}"
          sudo -E apt-get install -y ntpdate
          sudo -E ntpdate pool.ntp.org
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Create simulated physical disk
        id: disk
        run: |
          mnt_size=$(expr $(df -h /mnt | tail -1 | awk '{print $4}' | sed 's/[[:alpha:]]//g' | sed 's/\..*//') - 1)
          root_size=$(expr $(df -h / | tail -1 | awk '{print $4}' | sed 's/[[:alpha:]]//g' | sed 's/\..*//') - 4)
          sudo truncate -s "${mnt_size}"G /mnt/mnt.img
          sudo truncate -s "${root_size}"G /root.img
          sudo losetup /dev/loop6 /mnt/mnt.img
          sudo losetup /dev/loop7 /root.img
          sudo pvcreate /dev/loop6
          sudo pvcreate /dev/loop7
          sudo vgcreate github /dev/loop6 /dev/loop7
          sudo lvcreate -n runner -l 100%FREE github
          sudo mkfs.xfs /dev/github/runner
          sudo mkdir -p /builder
          sudo mount /dev/github/runner /builder
          sudo chown -R runner.runner /builder
          df -Th
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Install Docker
        id: install
        working-directory: /builder
        if: ${{ steps.disk.outputs.status }} == 'success' && !cancelled()
        run: |
          df -hT ${PWD}
          curl -fsSL https://get.docker.com | sh
          sudo usermod -aG docker $USER
          sudo newgrp docker
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Pull Docker Image [ ${{ inputs.docker_image }} ]
        id: pull
        working-directory: /builder
        if: ${{ steps.install.outputs.status }} == 'success' && !cancelled()
        run: |
          # Create a docker mapping directory
          mkdir -p /builder/compile-kernel/{kernel,output}
          ln -sf /builder/compile-kernel/kernel /home/runner/work/_actions/ophub/amlogic-s9xxx-armbian/main/compile-kernel/kernel
          ln -sf /builder/compile-kernel/output /home/runner/work/_actions/ophub/amlogic-s9xxx-armbian/main/compile-kernel/output

          # Pull the Armbian Docker image
          docker run -d --privileged \
              --name armbian-ophub \
              -v /builder/compile-kernel:/opt/kernel/compile-kernel \
              --restart=always \
              ophub/armbian-${{ inputs.docker_image }}:latest

          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Compile the kernel [ ${{ inputs.kernel_version }} ]
        uses: ophub/amlogic-s9xxx-armbian@main
        if: ${{ steps.pull.outputs.status }} == 'success' && !cancelled()
        with:
          build_target: kernel
          kernel_source: ${{ inputs.kernel_source }}
          kernel_version: ${{ inputs.kernel_version }}
          kernel_auto: ${{ inputs.kernel_auto }}
          delete_source: ${{ inputs.delete_source }}
          kernel_package: ${{ inputs.kernel_package }}
          kernel_toolchain: ${{ inputs.kernel_toolchain }}
          kernel_sign: ${{ inputs.kernel_sign }}
          kernel_config: ${{ inputs.kernel_config }}
          compress_format: ${{ inputs.compress_format }}

      - name: Upload Kernel to Release
        uses: ncipollo/release-action@main
        if: ${{ env.PACKAGED_STATUS }} == 'success' && !cancelled()
        with:
          tag: kernel_h6
          artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            - The kernel can be used to compile Armbian and OpenWrt.
            - The kernel source code comes from: ${{ inputs.kernel_source }}
            - The kernel compilation toolchain: ${{ inputs.kernel_toolchain }}
            - This is a dedicated kernel for `Allwinner H6 (TQC-A01)` and is not compatible with other series.
            - 这是 `全志 H6（TQC-A01）` 设备的专用内核，和其他系列不通用。
